export const ADD_USERS = 'ADD_USERS';
export const USERS_LOADING = 'USERS_LOADING';
export const USERS_FAILED = 'USERS_FAILED';

export const ADD_ROLES = 'ADD_ROLES';
export const ROLES_LOADING = 'ROLES_LOADING';
export const ROLES_FAILED = 'ROLES_FAILED';

export const ADD_ROLE = 'ADD_ROLE';
export const ROLE_LOADING = 'ROLE_LOADING';
export const ROLE_FAILED = 'ROLE_FAILED';

export const ADD_APPLICATIONS = 'ADD_APPLICATIONS';
export const APPLICATIONS_LOADING = 'APPLICATIONS_LOADING';
export const APPLICATIONS_FAILED = 'APPLICATIONS_FAILED';

export const ADD_APPLICATION = 'ADD_APPLICATION';
export const APPLICATION_LOADING = 'APPLICATION_LOADING';
export const APPLICATION_FAILED = 'APPLICATION_FAILED';

/*
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const PRODUCT_LOADING = 'PRODUCT_LOADING';
export const PRODUCT_FAILED = 'PRODUCT_FAILED';

export const ADD_SERVICE = 'ADD_SERVICE';
export const SERVICE_LOADING = 'SERVICE_LOADING';
export const SERVICE_FAILED = 'SERVICE_FAILED';
*/